auto:	          true

markdown:         maruku
paginate:         6
permalink:        /:title

title:            BeiYuu.com
url:              http://beiyuu.com
feed:             /atom.xml
author:
    name:         BeiYuu
description:      "BeiYuu\'s Blog"
author_info:      <a href="http://beiyuu.com/">BeiYuu</a>
